// SPDX-FileCopyrightText: © 2026 David Stainton
// SPDX-License-Identifier: AGPL-3.0-only

package combiner_test

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	"filippo.io/mlkem768"

	"github.com/katzenpost/hpqc/kem/adapter"
	"github.com/katzenpost/hpqc/kem/combiner"
	"github.com/katzenpost/hpqc/nike/x25519"
	"github.com/katzenpost/hpqc/rand"
)

// hybridVector mirrors CryptWalker/KEM/mlkem768_x25519_combiner_test.lean's
// Vec fields, produced by CryptWalker's
// gen_mlkem768_x25519_combiner_vectors.lean.
type hybridVector struct {
	Name                         string `json:"name"`
	PRF                          string `json:"prf"`
	X25519StaticPrivateKeyHex    string `json:"x25519_static_private_key_hex"`
	X25519StaticPublicKeyHex     string `json:"x25519_static_public_key_hex"`
	X25519EphemeralPrivateKeyHex string `json:"x25519_ephemeral_private_key_hex"`
	X25519CiphertextHex          string `json:"x25519_ciphertext_hex"`
	X25519SharedSecretHex        string `json:"x25519_shared_secret_hex"`
	MLKEMDHex                    string `json:"mlkem_d_hex"`
	MLKEMZHex                    string `json:"mlkem_z_hex"`
	MLKEMMHex                    string `json:"mlkem_m_hex"`
	MLKEMEncapsulationKeyHex     string `json:"mlkem_encapsulation_key_hex"`
	MLKEMCiphertextHex           string `json:"mlkem_ciphertext_hex"`
	MLKEMSharedSecretHex         string `json:"mlkem_shared_secret_hex"`
	CombinedCiphertextHex        string `json:"combined_ciphertext_hex"`
	CombinedSharedSecretHex      string `json:"combined_shared_secret_hex"`
}

type hybridVectorFile struct {
	Primitive string         `json:"primitive"`
	Vectors   []hybridVector `json:"vectors"`
}

// TestLeanMLKEM768X25519CombinerVectors checks vectors generated by
// CryptWalker's Lean port (gen_mlkem768_x25519_combiner_vectors.lean):
// reconstructs each component from the recorded raw inputs using hpqc's own
// code and confirms agreement on every intermediate and combined value.
func TestLeanMLKEM768X25519CombinerVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/lean_mlkem768_x25519_combiner_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var f hybridVectorFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("unmarshal vectors: %v", err)
	}
	if f.Primitive != "mlkem768_x25519_combiner" {
		t.Fatalf("unexpected primitive: %s", f.Primitive)
	}
	if len(f.Vectors) == 0 {
		t.Fatal("no vectors")
	}

	for _, v := range f.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			prf, err := adapter.PRFByName(v.PRF)
			if err != nil {
				t.Fatalf("resolve PRF: %v", err)
			}
			x25519KEM := adapter.FromNIKEWithPRF(x25519.Scheme(rand.Reader), prf)

			staticPrivBytes := mustHexDecode(t, v.X25519StaticPrivateKeyHex)
			ephPrivBytes := mustHexDecode(t, v.X25519EphemeralPrivateKeyHex)

			staticPriv, err := x25519KEM.UnmarshalBinaryPrivateKey(staticPrivBytes)
			if err != nil {
				t.Fatalf("unmarshal static private key: %v", err)
			}
			ephPriv, err := x25519KEM.UnmarshalBinaryPrivateKey(ephPrivBytes)
			if err != nil {
				t.Fatalf("unmarshal ephemeral private key: %v", err)
			}
			staticPubBytes, err := staticPriv.Public().MarshalBinary()
			if err != nil {
				t.Fatalf("marshal static public key: %v", err)
			}
			ephPubBytes, err := ephPriv.Public().MarshalBinary()
			if err != nil {
				t.Fatalf("marshal ephemeral public key: %v", err)
			}
			ctX25519 := ephPubBytes
			ssX25519, err := x25519KEM.Decapsulate(staticPriv, ctX25519)
			if err != nil {
				t.Fatalf("x25519 decapsulate: %v", err)
			}
			checkHex(t, "x25519 static public key", v.X25519StaticPublicKeyHex, staticPubBytes)
			checkHex(t, "x25519 ciphertext", v.X25519CiphertextHex, ctX25519)
			checkHex(t, "x25519 shared secret", v.X25519SharedSecretHex, ssX25519)

			dBytes := mustHexDecode(t, v.MLKEMDHex)
			zBytes := mustHexDecode(t, v.MLKEMZHex)
			mBytes := mustHexDecode(t, v.MLKEMMHex)
			seed := append(append([]byte{}, dBytes...), zBytes...)
			dk, err := mlkem768.NewKeyFromSeed(seed)
			if err != nil {
				t.Fatalf("mlkem768 new key from seed: %v", err)
			}
			ek := dk.EncapsulationKey()
			checkHex(t, "mlkem768 encapsulation key", v.MLKEMEncapsulationKeyHex, ek)
			ctMLKEM, ssMLKEM, err := mlkem768.EncapsulateDerand(ek, mBytes)
			if err != nil {
				t.Fatalf("mlkem768 encapsulate derand: %v", err)
			}
			checkHex(t, "mlkem768 ciphertext", v.MLKEMCiphertextHex, ctMLKEM)
			checkHex(t, "mlkem768 shared secret", v.MLKEMSharedSecretHex, ssMLKEM)

			ctCombined := append(append([]byte{}, ctX25519...), ctMLKEM...)
			checkHex(t, "combined ciphertext", v.CombinedCiphertextHex, ctCombined)
			ssCombined, err := combiner.SplitPRF([][]byte{ssX25519, ssMLKEM}, [][]byte{ctX25519, ctMLKEM})
			if err != nil {
				t.Fatalf("SplitPRF: %v", err)
			}
			checkHex(t, "combined shared secret", v.CombinedSharedSecretHex, ssCombined)
		})
	}
}

func mustHexDecode(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex decode %q: %v", s, err)
	}
	return b
}

func checkHex(t *testing.T, label, wantHex string, got []byte) {
	t.Helper()
	want := mustHexDecode(t, wantHex)
	if !bytes.Equal(want, got) {
		t.Errorf("%s mismatch:\n want %x\n got  %x", label, want, got)
	}
}
