ARG BASE=docker.io/debian:13
FROM ${BASE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential ca-certificates debhelper dh-golang \
		dpkg-dev git golang-any make \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /build
