# SPDX-FileCopyrightText: © 2026 David Stainton
# SPDX-License-Identifier: AGPL-3.0-only
"""The Python generator reproduces the committed BACAP vector files.

The files are generated by Go from testvectors/bacap/inputs.json; generating
them here from the same inputs with the Python port must give the same values.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from hpqc.bacap.gen_vectors import FILE_ORDER, generate

VECTORS_DIR = Path(__file__).parent / "vectors"


@pytest.fixture(scope="module")
def generated() -> dict:
    return generate(json.loads((VECTORS_DIR / "inputs.json").read_text()))


@pytest.mark.parametrize("name", FILE_ORDER)
def test_generated_matches_committed(generated: dict, name: str) -> None:
    committed = json.loads((VECTORS_DIR / f"{name}.json").read_text())
    assert generated[name] == committed, f"{name}.json differs from what inputs.json generates"
