// SPDX-FileCopyrightText: © 2026 David Stainton
// SPDX-License-Identifier: AGPL-3.0-only

package bacap

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/katzenpost/hpqc/sign/ed25519"
)

// These tests consume the BACAP-level vector files generated by
// testvectors/cmd/generate. The same files are read by the Python port
// at py/tests/bacap/test_bacap_vectors.py, so any divergence between
// implementations surfaces here on whichever side runs first.

func loadBACAPVectorFile(t *testing.T, name string, primitive string, into any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	require.NoError(t, err)
	var envelope struct {
		FormatVersion int             `json:"format_version"`
		Primitive     string          `json:"primitive"`
		Vectors       json.RawMessage `json:"vectors"`
	}
	require.NoError(t, json.Unmarshal(raw, &envelope))
	require.Equal(t, 1, envelope.FormatVersion, "format_version mismatch")
	require.Equal(t, primitive, envelope.Primitive, "primitive name mismatch")
	require.NoError(t, json.Unmarshal(envelope.Vectors, into))
}

func mustHexBytes(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	require.NoError(t, err)
	return b
}

func TestBACAPMessageBoxIndexVectors(t *testing.T) {
	var vectors []struct {
		Name             string `json:"name"`
		InitialIndexHex  string `json:"initial_index_hex"`
		AdvanceTo        uint64 `json:"advance_to"`
		ExpectedIndexHex string `json:"expected_index_hex"`
	}
	loadBACAPVectorFile(t, "message_box_index.json", "bacap_message_box_index", &vectors)
	require.NotEmpty(t, vectors)

	for _, v := range vectors {
		t.Run(v.Name, func(t *testing.T) {
			initial, err := NewEmptyMessageBoxIndexFromBytes(mustHexBytes(t, v.InitialIndexHex))
			require.NoError(t, err)
			advanced, err := initial.AdvanceIndexTo(v.AdvanceTo)
			require.NoError(t, err)
			actual, err := advanced.MarshalBinary()
			require.NoError(t, err)
			require.Equal(t, mustHexBytes(t, v.ExpectedIndexHex), actual,
				"advanced MessageBoxIndex bytes do not match expected")
		})
	}
}

func TestBACAPBoxIDVectors(t *testing.T) {
	var vectors []struct {
		Name             string `json:"name"`
		WriteCapHex      string `json:"writecap_hex"`
		AdvanceBy        uint64 `json:"advance_by"`
		CtxHex           string `json:"ctx_hex"`
		UseContext       bool   `json:"use_context"`
		ExpectedBoxIDHex string `json:"expected_box_id_hex"`
	}
	loadBACAPVectorFile(t, "box_id.json", "bacap_box_id", &vectors)
	require.NotEmpty(t, vectors)

	for _, v := range vectors {
		t.Run(v.Name, func(t *testing.T) {
			wc, err := NewWriteCapFromBytes(mustHexBytes(t, v.WriteCapHex))
			require.NoError(t, err)
			rc := wc.ReadCap()
			idx := wc.GetFirstMessageBoxIndex()
			if v.AdvanceBy > 0 {
				idx, err = idx.AdvanceIndexTo(idx.Idx64 + v.AdvanceBy)
				require.NoError(t, err)
			}
			ctx := mustHexBytes(t, v.CtxHex)
			expected := mustHexBytes(t, v.ExpectedBoxIDHex)

			var got []byte
			if v.UseContext {
				got = idx.BoxIDForContext(rc, ctx).Bytes()
			} else {
				// DeriveMessageBoxID needs the root pubkey; recover it
				// from the WriteCap blob (bytes [32:64]).
				rootPub := new(ed25519.PublicKey)
				require.NoError(t, rootPub.FromBytes(mustHexBytes(t, v.WriteCapHex)[32:64]))
				got = idx.DeriveMessageBoxID(rootPub).Bytes()
			}
			require.Equal(t, expected, got, "box ID mismatch")
		})
	}
}

func TestBACAPMutateKDFStateVectors(t *testing.T) {
	var vectors []struct {
		Name             string `json:"name"`
		WriteCapHex      string `json:"writecap_hex"`
		AdvanceBy        uint64 `json:"advance_by"`
		SaltHex          string `json:"salt_hex"`
		ReadCtxHex       string `json:"read_ctx_hex"`
		ExpectedIndexHex string `json:"expected_mutated_index_hex"`
		ExpectedBoxIDHex string `json:"expected_mutated_box_id_hex"`
	}
	loadBACAPVectorFile(t, "mutate_kdf_state.json", "bacap_mutate_kdf_state", &vectors)
	require.NotEmpty(t, vectors)

	for _, v := range vectors {
		t.Run(v.Name, func(t *testing.T) {
			wc, err := NewWriteCapFromBytes(mustHexBytes(t, v.WriteCapHex))
			require.NoError(t, err)
			rc := wc.ReadCap()
			idx := wc.GetFirstMessageBoxIndex()
			if v.AdvanceBy > 0 {
				idx, err = idx.AdvanceIndexTo(idx.Idx64 + v.AdvanceBy)
				require.NoError(t, err)
			}

			mutated := idx.MutateKDFState(mustHexBytes(t, v.SaltHex))
			actual, err := mutated.MarshalBinary()
			require.NoError(t, err)
			require.Equal(t, mustHexBytes(t, v.ExpectedIndexHex), actual, "mutated index mismatch")

			boxID := mutated.BoxIDForContext(rc, mustHexBytes(t, v.ReadCtxHex)).Bytes()
			require.Equal(t, mustHexBytes(t, v.ExpectedBoxIDHex), boxID, "mutated box ID mismatch")
		})
	}
}

func TestBACAPEncryptVectors(t *testing.T) {
	var vectors []struct {
		Name                 string `json:"name"`
		WriteCapHex          string `json:"writecap_hex"`
		AdvanceBy            uint64 `json:"advance_by"`
		CtxHex               string `json:"ctx_hex"`
		PlaintextHex         string `json:"plaintext_hex"`
		ExpectedBoxIDHex     string `json:"expected_box_id_hex"`
		ExpectedCiphertext   string `json:"expected_ciphertext_hex"`
		ExpectedSignatureHex string `json:"expected_signature_hex"`
	}
	loadBACAPVectorFile(t, "encrypt.json", "bacap_encrypt", &vectors)
	require.NotEmpty(t, vectors)

	for _, v := range vectors {
		t.Run(v.Name, func(t *testing.T) {
			wc, err := NewWriteCapFromBytes(mustHexBytes(t, v.WriteCapHex))
			require.NoError(t, err)
			idx := wc.GetFirstMessageBoxIndex()
			if v.AdvanceBy > 0 {
				idx, err = idx.AdvanceIndexTo(idx.Idx64 + v.AdvanceBy)
				require.NoError(t, err)
			}
			ctx := mustHexBytes(t, v.CtxHex)
			plaintext := mustHexBytes(t, v.PlaintextHex)

			boxID, ct, sig := idx.EncryptForContext(wc, ctx, plaintext)

			require.Equal(t, mustHexBytes(t, v.ExpectedBoxIDHex), boxID[:], "box ID mismatch")
			require.True(t, bytes.Equal(mustHexBytes(t, v.ExpectedCiphertext), ct), "ciphertext mismatch")
			require.Equal(t, mustHexBytes(t, v.ExpectedSignatureHex), sig, "signature mismatch")

			// Round-trip decrypt as a sanity check.
			recovered, err := idx.DecryptForContext(boxID, ctx, ct, sig)
			require.NoError(t, err)
			require.Equal(t, plaintext, recovered, "decrypt round-trip mismatch")
		})
	}
}
