name: MacOS Golang build and test

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Display Go version
        shell: bash
        run: go version

      - name: Install golang dependencies
        shell: bash
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
        run: go get -v ./...

      - name: Build golang
        shell: bash
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
        run: go build -v ./...

      - name: Golang test
        shell: bash
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
          CGO_LDFLAGS: -Wl,-stack_size,0x1F40000
        run: go test -v ./...
