name: Go cross compile

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CC: ["clang"]
        ARCH: ["arm32v5", "arm32v7", "i386", "arm64", "mips64", "mips64le", "mips", "mipsle", "ppc64", "ppc64le", "s390x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Golang cross-compilation deps
        run: sudo ./misc/install-debian-go-deps-by-arch.sh ${{ matrix.ARCH }}
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Display Go version
        run: go version
      - name: Run tests
        env:
          CGO_LDFLAGS: -Wl,-z,stack-size=0x1F40000
        run: go test -v ./...
