name: Windows Msys2 64bit (cygwin,msvcrt,ucrt) gcc golang build and test

on: [pull_request]

permissions:
  contents: read

jobs:
  windows-build-and-test-golang:
    runs-on: windows-2022
    strategy:
      matrix:
        ENVIRONMENT: ["UCRT64", "MINGW64"] # https://www.msys2.org/docs/environments/
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.ENVIRONMENT }}
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gcc
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-ucrt-x86_64-go
            make
            git
            gcc

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Gather runtime environment
        shell: msys2 {0}
        run: |
         echo ${{ matrix.ENVIRONMENT }}
         uname -a
         bash --version
         gcc -v
         go version

      - name: Install golang dependencies
        shell: msys2 {0}
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
          GOTOOLCHAIN: auto
        run: go get -v ./...

      - name: Build golang
        shell: msys2 {0}
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
          GOTOOLCHAIN: auto
          GOEXPERIMENT: cgocheck2
          GODEBUG: cgocheck=1
          CGO_LDFLAGS: "-Wl,--no-as-needed -Wl,-allow-multiple-definition"
        run: go build -v ./...

      - name: Golang test
        shell: msys2 {0}
        env:
          HIGHCTIDH_PORTABLE: "1"
          CGO_ENABLED: "1"
          GOTOOLCHAIN: auto
          GOEXPERIMENT: cgocheck2
          GODEBUG: cgocheck=1
          CGO_LDFLAGS: "-Wl,--no-as-needed -Wl,-allow-multiple-definition"
        run: go test -v ./...
